### ISSUE TITLE
Mirai advisory from AT&T

### ISSUE THREAD

**Issue by scott23192** [DShield-ISC/dshield#96]
Receiving the following from ISP - they go on to provide general instructions on how to find and harden the affected device.  The IP reported is a static IP assigned to my DShield Rasp-Pi Honeypot.  Should I wipe & rebuild the device?  
====================
Mirai advisory from AT&T Internet Services Security Center

AT&T Managed Internet Services Site-ID: xxxxxxxxxxxxx
Circuit ID: xxxxxxxxxxxxxxxxxxxx

AT&T has received information indicating that one or more devices
using your Internet connection may be infected with malicious
software. Internet traffic consistent with a Mirai infection was
observed on Dec 11, 2017 at 3:59 AM CST from the IP address
12.155.125.10. Our records indicate that this IP address was
assigned to you at this time.
====================

**Comment by jullrich** [comment]
Likely they misidentify your honeypot as a vulnerable device. It is highly unlikely that it is infected. But the honeypot will react to probes just like a vulnerable system.

 

Have you changed your Raspberry Pi’s password from the default (our install script should check for that). But if you didn’t, then there is a possibility that it got infected. To be on the safe site, you may want to re-install the honeypot. 

 

 

Johannes B. Ullrich, Ph.D., Dean of Research, SANS Technology Institute

Join us for SANS 2018 (April 3-10) in Orlando, Florida, and choose from over 45 InfoSec courses taught by real-world practitioners, plus three types of NetWars, a Vendor Solutions Expo, and networking opportunities at several exciting Bonus Sessions. Register now: http://www.sans.org/u/yJ9

**Comment by scott23192** [comment]
Thank you for the reply!  The Pi password was changed and SSH login is also secured by private key.

So, I will consider it a false alert from the ISP.

**Comment by gebhard73** [comment]
What makes me uneasy is the "from" stuff:
"Internet traffic consistent with a Mirai infection was observed on [...] **from** the IP address" because the honey pot should not send anythnig.

Hopefully somebody wasn't lucky phrasing this correctly and what they really wanted to say would have been: "we found a telnet server and were able to log in using 'Mirai' credentials" ... but  they may not be allowed to do so at all ...

Any chance going through the logs (messages, cowrie) having a look at the mentioned time frame if a connections from an AT&T IP address happend at that time?
